<?php

namespace Contributte\Mail\Tracy\Template;

use Tracy\Dumper;

?>

<h1>Contributte/Mails</h1>

<div class="tracy-inner">
    <div class="tracy-inner-container">

        <?php // Display mails ?>
        <h2>Sent mails</h2>

        <?php for ($i = 0; $i < count($mails); $i++): ?>
            <table>

                <?php // Display mail headers ?>
                <?php foreach ($mails[$i]->getHeaders() as $k => $v): ?>
                    <tr>
                        <th><?php echo $k; ?></th>
                        <td><?php echo Dumper::toHtml($v); ?></td>
                    </tr>
                <?php endforeach; ?>

                <?php // Display mail preview ?>
                <?php if (!empty($mails[$i]->getHtmlBody())): ?>
                    <tr>
                        <td style="background-color:#ffffff;padding: 0" colspan="2">
                            <iframe style="width:100%;height:225px"
                                    srcdoc="<?php echo str_replace('"', '&quot;', $mails[$i]->getHtmlBody()); ?>"
                            ></iframe>
                        </td>
                    </tr>
                <?php endif; ?>

            </table>

            <?php // Some space  after every mail ?>
            <?php echo $i < (count($mails) - 1) ? '<br>' : ''; ?>
        <?php endfor; ?>

    </div>
</div>
