<h1>Mails</h1>

<div class="tracy-inner">
    <div class="tracy-inner-container">

        <?php for ($i = 0, $iMax = count($mails); $i < $iMax; $i++): ?>
            <table>

                <?php // Display mail headers ?>
                <?php foreach ($mails[$i]->getHeaders() as $k => $v): ?>
                    <tr>
                        <th><?= $k; ?></th>
                        <td><?= Tracy\Dumper::toHtml($v); ?></td>
                    </tr>
                <?php endforeach; ?>

                <?php if (!empty($mails[$i]->getHtmlBody())): ?>
                    <tr>
                        <td style="background-color:#ffffff;padding: 0" colspan="2">
                            <iframe style="width:100%;height:225px"
                                    srcdoc="<?= str_replace('"', '&quot;', $mails[$i]->getHtmlBody()); ?>"
                            ></iframe>
                        </td>
                    </tr>
                <?php endif; ?>

            </table>

            <?= $i < ($iMax - 1) ? '<br>' : ''; ?>
        <?php endfor; ?>

    </div>
</div>
